INSERT OR REPLACE INTO sucursales (id, code, name) VALUES
  (10034, 'CO', 'Coaque'),
  (27, 'NM', 'Matriz NM'),
  (1, 'NA', 'Naturisa'),
  (2, 'PE', 'Pesjoya'),
  (10035, 'JU', 'Juananu'),
  (3, 'MA', 'Maricultura'),
  (4, 'KA', 'Kamaclusa'),
  (5, 'JO', 'Josefina'),
  (6, 'BR', 'Biorey'),
  (7, 'CR', 'Camino Real'),
  (8, 'CA', 'Camaron'),
  (9, 'MH', 'Marchena'),
  (10, 'MG', 'Margolfo'),
  (11, 'ES', 'Esteromar'),
  (12, 'RN', 'Rio Nilo'),
  (18, 'LA', 'Lanconor'),
  (17, 'GO', 'Golfomar'),
  (20, 'RO', 'Roblemar'),
  (19, 'BO', 'Bonanza'),
  (21, 'LG', 'Los Gelices'),
  (15, 'IN', 'Inducam'),
  (16, 'GR', 'Granmar'),
  (13, 'A1', 'Acualit 1'),
  (28, 'A2', 'Acualit 2'),
  (14, 'FI', 'Fincacua'),
  (23, 'LQ1', 'Larviquest 1'),
  (10033, 'SC', 'Solcamaron'),
  (30, 'AR', 'Acopio Río Nilo'),
  (24, 'LQ2', 'Larviquest 2'),
  (25, 'LQ3', 'Larviquest 3'),
  (26, 'LQ4', 'Larviquest 4'),
  (29, 'AP', 'Acopio Pesjoya'),
  (33, 'NC', 'Coaque NC'),
  (31, 'RM', 'Matriz RM'),
  (32, 'AM', 'Matriz AM'),
  (10036, 'NX', 'Matriz NX');
