name: Alerta Piscinas Sin Movimiento - Diario

on:
  #schedule:
   # - cron: '30 1 * * *'   # 20:30 Ecuador
    #- cron: '30 3 * * *'   # 22:30 Ecuador
  workflow_dispatch:

jobs:
  reporte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests pandas openpyxl
      - name: Ejecutar reporte
        env:
          NATURISA_PASSWORD: ${{ secrets.NATURISA_PASSWORD }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: python reporte_diario.py
